-- MySQL Script generated by MySQL Workbench
-- Sun May  4 22:24:30 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sistema_mega` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`CURSOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CURSOS` (
  `id_curso` INT NOT NULL AUTO_INCREMENT,
  `nombre_curso` VARCHAR(45) NULL,
  PRIMARY KEY (`id_curso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`USUARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`USUARIOS` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `correo` VARCHAR(45) NULL,
  `contrasenia` VARCHAR(45) NULL,
  `estado` TINYINT NULL,
  `rol` VARCHAR(20) NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SEDES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SEDES` (
  `id_sede` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `distrito` VARCHAR(45) NULL,
  PRIMARY KEY (`id_sede`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PROFESORES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PROFESORES` (
  `id_profesores` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `dni` VARCHAR(45) NULL,
  `USUARIOS_id_usuario` INT NOT NULL,
  `SEDES_id_sede` INT NOT NULL,
  PRIMARY KEY (`id_profesores`),
  CONSTRAINT `fk_PROFESORES_USUARIOS1`
    FOREIGN KEY (`USUARIOS_id_usuario`)
    REFERENCES `mydb`.`USUARIOS` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PROFESORES_SEDES1`
    FOREIGN KEY (`SEDES_id_sede`)
    REFERENCES `mydb`.`SEDES` (`id_sede`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_PROFESORES_USUARIOS1_idx` ON `mydb`.`PROFESORES` (`USUARIOS_id_usuario` ASC) VISIBLE;

CREATE INDEX `fk_PROFESORES_SEDES1_idx` ON `mydb`.`PROFESORES` (`SEDES_id_sede` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`CURSOS_has_PROFESORES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CURSOS_has_PROFESORES` (
  `CURSOS_id_curso` INT NOT NULL,
  `PROFESORES_id_profesores` INT NOT NULL,
  PRIMARY KEY (`CURSOS_id_curso`, `PROFESORES_id_profesores`),
  CONSTRAINT `fk_CURSOS_has_PROFESORES_CURSOS`
    FOREIGN KEY (`CURSOS_id_curso`)
    REFERENCES `mydb`.`CURSOS` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CURSOS_has_PROFESORES_PROFESORES1`
    FOREIGN KEY (`PROFESORES_id_profesores`)
    REFERENCES `mydb`.`PROFESORES` (`id_profesores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_CURSOS_has_PROFESORES_PROFESORES1_idx` ON `mydb`.`CURSOS_has_PROFESORES` (`PROFESORES_id_profesores` ASC) VISIBLE;

CREATE INDEX `fk_CURSOS_has_PROFESORES_CURSOS_idx` ON `mydb`.`CURSOS_has_PROFESORES` (`CURSOS_id_curso` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`ASISTENCIAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ASISTENCIAS` (
  `id_asistencia` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL,
  `presente` TINYINT NULL,
  `PROFESORES_id_profesores` INT NOT NULL,
  PRIMARY KEY (`id_asistencia`),
  CONSTRAINT `fk_ASISTENCIAS_PROFESORES1`
    FOREIGN KEY (`PROFESORES_id_profesores`)
    REFERENCES `mydb`.`PROFESORES` (`id_profesores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ASISTENCIAS_PROFESORES1_idx` ON `mydb`.`ASISTENCIAS` (`PROFESORES_id_profesores` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`ADMINISTRADORES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ADMINISTRADORES` (
  `id_administrador` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `dni` VARCHAR(45) NULL,
  `USUARIOS_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_administrador`),
  CONSTRAINT `fk_ADMINISTRADORES_USUARIOS1`
    FOREIGN KEY (`USUARIOS_id_usuario`)
    REFERENCES `mydb`.`USUARIOS` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ADMINISTRADORES_USUARIOS1_idx` ON `mydb`.`ADMINISTRADORES` (`USUARIOS_id_usuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`ESTUDIANTES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ESTUDIANTES` (
  `id_estudiantes` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `dni` VARCHAR(45) NULL,
  `USUARIOS_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_estudiantes`),
  CONSTRAINT `fk_ESTUDIANTES_USUARIOS1`
    FOREIGN KEY (`USUARIOS_id_usuario`)
    REFERENCES `mydb`.`USUARIOS` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ESTUDIANTES_USUARIOS1_idx` ON `mydb`.`ESTUDIANTES` (`USUARIOS_id_usuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`CICLOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CICLOS` (
  `id_ciclo` INT NOT NULL AUTO_INCREMENT,
  `nombre_ciclo` VARCHAR(45) NULL,
  `modalidad` VARCHAR(45) NULL,
  `costo` DECIMAL NULL,
  `fecha_inicio` DATE NULL,
  `fecha_fin` DATE NULL,
  PRIMARY KEY (`id_ciclo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SEDES_has_CICLOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SEDES_has_CICLOS` (
  `SEDES_id_sede` INT NOT NULL,
  `CICLOS_id_ciclo` INT NOT NULL,
  PRIMARY KEY (`SEDES_id_sede`, `CICLOS_id_ciclo`),
  CONSTRAINT `fk_SEDES_has_CICLOS_SEDES1`
    FOREIGN KEY (`SEDES_id_sede`)
    REFERENCES `mydb`.`SEDES` (`id_sede`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SEDES_has_CICLOS_CICLOS1`
    FOREIGN KEY (`CICLOS_id_ciclo`)
    REFERENCES `mydb`.`CICLOS` (`id_ciclo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_SEDES_has_CICLOS_CICLOS1_idx` ON `mydb`.`SEDES_has_CICLOS` (`CICLOS_id_ciclo` ASC) VISIBLE;

CREATE INDEX `fk_SEDES_has_CICLOS_SEDES1_idx` ON `mydb`.`SEDES_has_CICLOS` (`SEDES_id_sede` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`INSCRIPCIONES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`INSCRIPCIONES` (
  `id_inscripciones` INT NOT NULL AUTO_INCREMENT,
  `ESTUDIANTES_id_estudiantes` INT NOT NULL,
  `CICLOS_id_ciclo` INT NOT NULL,
  PRIMARY KEY (`id_inscripciones`),
  CONSTRAINT `fk_INSCRIPCIONES_ESTUDIANTES1`
    FOREIGN KEY (`ESTUDIANTES_id_estudiantes`)
    REFERENCES `mydb`.`ESTUDIANTES` (`id_estudiantes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_INSCRIPCIONES_CICLOS1`
    FOREIGN KEY (`CICLOS_id_ciclo`)
    REFERENCES `mydb`.`CICLOS` (`id_ciclo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_INSCRIPCIONES_ESTUDIANTES1_idx` ON `mydb`.`INSCRIPCIONES` (`ESTUDIANTES_id_estudiantes` ASC) VISIBLE;

CREATE INDEX `fk_INSCRIPCIONES_CICLOS1_idx` ON `mydb`.`INSCRIPCIONES` (`CICLOS_id_ciclo` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`PAGOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PAGOS` (
  `id_pago` INT NOT NULL AUTO_INCREMENT,
  `monto` DECIMAL NULL,
  `fecha_pago` DATE NULL,
  `INSCRIPCIONES_id_inscripciones` INT NOT NULL,
  PRIMARY KEY (`id_pago`),
  CONSTRAINT `fk_PAGOS_INSCRIPCIONES1`
    FOREIGN KEY (`INSCRIPCIONES_id_inscripciones`)
    REFERENCES `mydb`.`INSCRIPCIONES` (`id_inscripciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_PAGOS_INSCRIPCIONES1_idx` ON `mydb`.`PAGOS` (`INSCRIPCIONES_id_inscripciones` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

